#!/bin/bash
#
# Ülesanne3
#
echo -n "Sisesta kell: "
read kell
if test $kell -gt 6 -a $kell -lt 12
then
echo "Tere hommikust!"
elif test $kell -ge 12 -a $kell -lt 18
then
echo "Tere paevast!"
elif test $kell -ge 18 -a $kell -lt 22
then
echo "Tere ohtust!"
elif [ $kell -ge 23 -a $kell -lt 24 ] || [ $kell -gt 0 -a $kell -le 6 ]
then
echo "Head ood!"
else
echo "Vigane sisend"
fi
#
# Skript lõppes
