#!/bin/bash
#
# Tervitusskript
#
echo -n "Tere, " #Väljastab ilma reavahetuseta
echo -n `whoami | cut -c1 | tr [:lower:] [:upper:]` #Väljastab esinime esi tähe suurelt
echo -n `whoami | cut -c2-` #Väljastab nime ülejäänud tähed väikeselt
echo -e "!" #Väljastab ! reavahetusega
#
# Skript lõppes

