#!/bin/bash
#
# Ülesanne1
#
echo -n "Sisesta oma ees- ja perenimi: " #väljastab selle teksti
read eesnimi perenimi #võtab ees  ja pere nime
echo "Sinu eesnimi on $eesnimi ja perenimi on $perenimi" #väljastab saadud andmed
#
# Skript lõppes

