#!/bin/bash
#
# Ülesanne1
#
echo -n "Sisesta oma ees- ja perenimi: " #väljastab selle teksti
read eesnimi perenimi #võtab ees  ja pere nime
echo "Tere tulemast, $eesnimi $perenimi" #väljastab saadud andmed
#
# Skript lõppes

