#!/bin/bash
#
# Ülesanne2
#
echo -n "Sisesta ridade arv: "
read ridadearv
echo -n "Sisesta tärnide arv reas: "
read tarnidearv
for (( i = 1; i <= ridadearv; i++ ))
do
echo -n "$i "
for (( j = 1; j <= tarnidearv; j++ ))
do
echo -n "*"
done
echo "" #### print the new line ###
done
done
#
# Skript lõppes
